### ISSUE TITLE
增加一个配置 可以选择过滤某根目录

### ISSUE THREAD

**Issue by jin10086** [TencentCloudBase/cloudbase-action#2]
因为我的网站源代码在 master 分支下 (https://github.com/jin10086/jin10086.github.io/tree/master

所以我的 staticSrcPath 是 ./

会把.git文件上传过去...

然后会出问题（详细见https://github.com/jin10086/jin10086.github.io/actions/runs/78549326

**Comment by binggg** [comment]
收到，我们加一下

**Comment by snowinszu** [comment]
遇到一样的问题

**Comment by jin10086** [comment]
@snowinszu 想到一个解决办法。。。先 删除.git 目录

**Comment by snowinszu** [comment]
@jin10086 .git不是默认push都要带上的吗

**Comment by jin10086** [comment]
@snowinszu 意思是push后,删除.git文件夹，再使用cloudbase-action,相当于自己手动过滤。。。

**Comment by AnonyStar-zz** [comment]
这个问题又没解决的大佬啊，闹心~~

**Comment by binggg** [comment]
@AnonyStar @jin10086 @snowinszu 
各位久等了，可以使用 v1.1.0 的action，支持过滤文件

### `staitcIgnore`

`v.1.1.0` 版本开始支持

静态资源部署时忽略的文件路径，支持通配符，例如`node_modules/**`, 多个路径可以用,隔开，默认值 `.git,.github,node_modules`

## 参考示例

例如项目中的静态资源存放在 `build` 目录，希望部署到云开发静态网站托管的根目录下

可以编写如下的 Github Action 文件 `.github/workflows/main.yml`

```yaml
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Tencent Cloudbase Github Action Example
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy static to Tencent CloudBase
        id: deployStatic
        uses: TencentCloudBase/cloudbase-action@v1.1.0
        with:
          secretId: ${{ secrets.SECRET_ID }}
          secretKey: ${{ secrets.SECRET_KEY }}
          envId: ${{ secrets.ENV_ID }}
          staticSrcPath: build
```
