### ISSUE TITLE
一直在uploading

### ISSUE THREAD

**Issue by Yrobot** [TencentCloudBase/cloudbase-action#28]
![image](https://user-images.githubusercontent.com/28182882/134370332-6e2b7db2-11fc-47e9-8f8c-aa674aa3d42f.png)

v1.1.1
单纯想把build上传到静态页面服务所以选了v1版本。
持续了30多分钟，还一直loading，没有任何报错

**Comment by zh30** [comment]
你好，看了它的源码，其实就是几条命令就好了，我自己写了三个 actions 的步骤，希望对你有帮助：

```yml
      - name: Install CloudBase-Cli
        run: npm install -g @cloudbase/cli
    
      - name: Login to Tencent CloudBase
        env:
          SECRET_ID: ${{secrets.secretId}}
          SECRET_KEY: ${{secrets.secretKey}}
        run: tcb login --apiKeyId "$SECRET_ID" --apiKey "$SECRET_KEY"
          
      - name: Deploy to Tencent CloudBase
        env:
          ENV_ID: ${{secrets.envId}}
        run: tcb framework deploy -e "$ENV_ID"
```
对应的secrets里面的字段，去项目设置里面添加即可。
